### PR TITLE
TSE - Code Review - Todo list project

### PR DESCRIPTION
**Pull request by simoxsimo**
the following steps were taken into consideration while building this project:
- Using Webpack to bundle and generate production files.
- Implementing objects using factory functions and modules (i.e: after including localStorage those objects were no longer needed).
- The use of localStorage to preserve user's data

### CODE REVIEW

**Review by Torres-ssf — CHANGES_REQUESTED** [review]
### Changes required :muscle: 
Hi there team :hand: 
Great work with this project :+1: :clap: 
But before moving on, there are some changes to be made.

- [x] The application logic should be separated from the DOM manipulations tasks. You can separate them into modules. It's also a best practice to place them in different files from the index file. Requirement [print](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/modules_requirement.png).

- [x] The applications should have a "default" project ready to be used. Requirement [print](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/javascript/todo_list/projects_requirement.png).

- [x] When a user tries to update a todo, the current todo values are not available in the inputs to be updated. This forces the user to fill in all values ​​again instead of just updating what they need.

- [x] Each Todo item must be a Javascript object. And its created by your App logic, outside from any DOM task manipulation.

Please kindly submit for code review again after making these changes.

Happy coding :computer: 
**Sergio Torres**

**Comment by simoxsimo** [comment]
Thank you for reviewing our project:

As for the following points:
>The application logic should be separated from the DOM manipulations tasks. You can separate them into modules. It's also a best practice to place them in different files from the index file. Requirement.

And

>Each Todo item must be a Javascript object. And its created by your App logic, outside from any DOM task manipulation.

I would say we already did that you can check _Edit/Delete Todos_ commit, the reason that those factories are no longer exist is that when we implemented _**localStorage**_ it becomes clear that we no longer need the factories rather than setting the instance data and then getting the same data again _( since we can only use getters to access instance data because state object is private )_ to store it inside localStorage where all that data are from form inputs drag down the design,
so I decided to directly store inside an object while using getItem/setItem so read/update values from localStorage.
So all the logic inside index.js is DOM logic with only setItem/getItem calls to write/read localStorage.
when an event is dispatched.

**Review by bellom — CHANGES_REQUESTED** [review]
## Hi Team  :clap: 

**Great work making `almost` all the necessary corrections from the previous review.**

**According to the previous review, you have been told to add `default project`**
(I started your app but I don't seem to see the default project 🤔 , I hope I didn't miss that.)
see the screenshot from your app below;
image

**_Kindly add a default project that user can see as soon as the user starts the app._**

### ♻️ Kindly re-submit for review after making all those changes :slightly_smiling_face: Thumps -up await you.....

**Best,**

**Oluwaseun Bello**
**_Slack Handle - @sean bellom_**

**Review by maelfosso — APPROVED** [review]
# Congratulations :clap: 

You can merge it :+1: 
Good continuation :handshake: 

Thanks
Mael FOSSO

**Pull request merged**
